# Generated by Django 6.0.6 on 2026-06-28 18:00

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('friends', '0003_friendreques_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RenameModel(
            old_name='FriendReques',
            new_name='FriendRequest',
        ),
    ]
